### ISSUE TITLE
couple quick suggestions

### ISSUE THREAD

**Issue by tmm** [EveripediaNetwork/wagmi-magic-connector#1]
Hi there! This is great work. I have a couple quick suggestions on how to improve things.

1. Use `@wagmi/core` instead of `wagmi` so folks can use this connector with the Vanilla JS client (and other frameworks in the future). I would also set `@wagmi/core` and `ethers` both as a peer dependencies too.
2. Switch imports to `@wagmi/core`. Everything being imported from `wagmi` can be switched to `@wagmi/core`. You can also import both `UserRejectedRequestError` and `normalizeChainId` from `@wagmi/core` instead of duplicating in this library.

**Comment by Royal-lobster** [comment]
Thanks for the suggestions !

**Comment by Royal-lobster** [comment]
@tmm Thanks for the feedback. We implemented the changes, But when moving back to using the package, it is not able to recognise the ```@wagmi/core``` from ```wagmi``` package and is expecting to install it separately so there are total 3 dependencies for users ```wagmi```, ```@wagmi/core```, and ```@everipedia/wagmi-magic-connector```. 

So we would love to know your opinion on which one is better - ```@wagmi/core``` as dependency or as peer-dependency

**Comment by tmm** [comment]
You could try adding `@wagmi/core` to `peerDependenciesMeta` in `package.json`:

```json
{
  "peerDependenciesMeta": {
    "@wagmi/core": {
      "optional": true
    }
  }
}
```

**Comment by Royal-lobster** [comment]
> You could try adding `@wagmi/core` to `peerDependenciesMeta` in `package.json`:

Thanks ! tried to place ```@wagmi/core``` in ```peerDependanciesMeta``` it but it seems the problem still persists. The error is happening in runtime : 

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/52039218/166255642-89569529-c355-428a-a1fc-7e435f617e53.png">

**Comment by tmm** [comment]
I see! Adding `@wagmi/core` as a hard dependency should be fine. Not planning any breaking changes for `0.3`.
