### ISSUE TITLE
"+" support in email address input

### ISSUE THREAD

**Issue by Aztriltus** [EveripediaNetwork/wagmi-magic-connector#28]
- **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [x] question about the decisions made in the repository
  - [ ] question about how to use this project

- **Summary**
Hey, I'm wondering what was the decision made for the email regex. Could we allow emails with + to work? E.g. `john.doe+magic@gmail.com`. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
I've tried modifying the existing email regex a little to account for `+`. 
```
^([a-zA-Z0-9_.-])+(\+[a-zA-Z0-9-]+)?@(([a-zA-Z0-9-])+.)+([a-zA-Z0-9]{2,4})
```

**Comment by Royal-lobster** [comment]
@Aztriltus Thanks for opening this issue. I will get this updated.

**Comment by Royal-lobster** [comment]
now we are supporting this in @everipedia/wagmi-magic-connector v0.6.5

**Comment by Aztriltus** [comment]
Thanks @Royal-lobster for the quick turnaround! 👍
