### ISSUE TITLE
How to get user email info once connected to WAGMI

### ISSUE THREAD

**Issue by allenchuang** [EveripediaNetwork/wagmi-magic-connector#31]
Hi, i was wondering if there's anyway to get user information once connected to WAGMI?

**Comment by Royal-lobster** [comment]
> Hi, i was wondering if there's anyway to get user information once connected to WAGMI?

Yes, we can obtain the information by accessing the connector from ```useAccount``` from wagmi

```javascript
const { connector } = useAccount()
connector.magicSDK.user.getMetadata().then(data => console.log(data))
```

check out https://magic.link/docs/auth/api-reference/client-side-sdks/web#getmetadata for more information
