### ISSUE TITLE
Doesn't work with latest versions of RainbowKit

### ISSUE THREAD

**Issue by brightiron** [EveripediaNetwork/wagmi-magic-connector#32]
- **I'm submitting a ...**
  [ x] bug report

- **Summary**
 - Using latest versions of rainbowkit with this connector does not open magic authentication modal. No errors are logged to the console. I've confirmed that it's not as simple as the modal appearing 'behind' the rainbowkit modal. The dom is never updated when clicking on the 'magic connector' from the rainbowkit modal, and the 'magic overlay' dom element never appears.
 
 - Connecting directly via wagmi useConnect works. So it seems as if the issue is specific to this connector and rainbowkit integration. 

- **Version** (e.g. 1.0.0)
  - @everipedia/wagmi-magic-connector version: 0.6.5
  - wagmi version: 0.7.3
  - @rainbow-me/rainbowkit version: 0.7.1
  - ethers version: 5.7.1

**Comment by tchataigner** [comment]
I think https://github.com/EveripediaNetwork/wagmi-magic-connector/pull/33 should be able to fix that. Please feel free to give a quick look!
