### ISSUE TITLE
Multiple networks in magicSdkConfiguration

### ISSUE THREAD

**Issue by brendanstockigt** [EveripediaNetwork/wagmi-magic-connector#37]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x ] question about how to use this project

- **Summary**
- Hi is there a way to add multiple networks to the magicSdkConfiguration and have the wallet able to use multiple chains?

- **Attachments** (e.g. screenshots, logs, source code, etc.)

- **Version** (e.g. 1.0.0)
  - @everipedia/wagmi-magic-connector version:
  - wagmi version:

**Comment by Royal-lobster** [comment]
@brendanstockigt  Sorry for the late response, i don't think there is support of multiple chains with magic, you can request a support on [magic.link](https://magic.link) website for more information.
