### ISSUE TITLE
Different Magic sign-in modal appears on page load after 7 days without any way to prevent it

### ISSUE THREAD

**Issue by robyn3choi** [EveripediaNetwork/wagmi-magic-connector#48]
**Describe the bug**
We are using `MagicConnectConnector` to display a sign-in modal when users click a "sign-in" button on our app (screenshot 1). We noticed that after 7 days of being signed in, a different sign-in modal appears on page load, without the user clicking anything. There doesn't seem to be any way to stop this modal from appearing, which interferes with our UX. Signing in with this modal also leads to unpredictable results, and we are unable to do things like catch errors thrown by the modal.

On Brave browser with Shields up, this happens on the next page load after signing in, instead of after 7 days. 

**To Reproduce**
Instead of waiting 7 days, you can reproduce this bug on Brave browser with Shields up.

1. Go to [alexandria-1hixot7fx-alexandria-labs.vercel.app/](https://alexandria-1hixot7fx-alexandria-labs.vercel.app/) on Brave browser
2. Click on "Sign in" at the top-right
3. Check the checkbox and click "Continue"
4. Click "Email"
5. Go through the email verification, then sign the message. You should see your wallet address in the top-right after a few seconds.
6. Refresh the page.
7. The Magic Auth modal will appear on page load.

**Expected behavior**
The sign-in modal that appears in step 7 should use Magic Connect instead of Magic Auth. We would also like the option to suppress this modal entirely since we are keeping track of the user's session separately and we sign them out when it expires.

**Screenshots**
The modal that appears when signing in properly:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/9066587/213811456-d842d341-068d-4f94-89fa-0ffd3abba86a.png">

The modal that appears after 7 days (or after page load on Brave):
<img width="459" alt="image" src="https://user-images.githubusercontent.com/9066587/213813140-bbfce85f-1627-4d42-b22f-a434e7ec1255.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1
 - Browser/version: Chrome 109.0.5414.87, Brave 1.47.171

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 15.6
 - Browser: Safari
 - Version 15.6

**Comment by robyn3choi** [comment]
I forgot to mention that this only happens if `autoconnect: true` when creating the wagmi client. But we do still want it to connect automatically, since we disconnect it when we detect that the user's session has expired.

**Comment by bruno3du** [comment]
Here I'm trying to use the second one and it is opening the auth one, which I didn't want to.

**Comment by Royal-lobster** [comment]
> Here I'm trying to use the second one and it is opening the auth one, which I didn't want to.

I think this is because the magic connector is also using the same modal as auth. probably we can use the native modal for magic connector.

**Comment by robyn3choi** [comment]
I think what's causing the auth modal to popup is the `https://auth.magic.link/v1/session/refresh` api call which happens when `magic.user.isLoggedIn()` is called. Our app isn't using this method but maybe it's being called by `wagmi-magic-connector` or the magic sdk itself.

**Comment by Royal-lobster** [comment]
I hope the pr fixes the issue. please reopen if it is still a issue.
